events_logging.config:
  type: config_object
  label: 'Events Logging Configuration'
  mapping:
    enabled_events_logging_plugins:
      type: sequence
      sequence:
        type: string
    enabled_content_entities:
      type: sequence
      sequence:
        type: string
    enabled_config_entities:
      type: sequence
      sequence:
        type: string
